version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # Newer versions expect a vcpkg manifest, so stick to v7, that could handle vcpkgArguments
      - dependency-name: "lukka/run-vcpkg"
    groups:
      github-actions:
        patterns:
          - "*"
