---
name: build

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
  push:
    branches:
      - openbsd-ci-fix
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'

permissions: read-all

jobs:
  freebsd-cmake-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci/freebsd skip') && !contains(github.event.head_commit.message, 'ci/freebsd/cmake skip')"
    strategy:
      fail-fast: false
      matrix:
        release: ["13.2", "14.0"]
        EVENT_MATRIX:
          - NONE
          - NO_SSL
          - DISABLE_OPENSSL
          - DISABLE_THREAD_SUPPORT
          - DISABLE_DEBUG_MODE
          - DISABLE_MM_REPLACEMENT
          - TEST_EXPORT_STATIC
          - TEST_EXPORT_SHARED

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: freebsd-${{ matrix.release }}-cmake-${{ matrix.EVENT_MATRIX }}-v1

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: |
            pkg install -y  mbedtls cmake python3
          usesh: true
          run: |
            if [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_OPENSSL" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_OPENSSL=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "NO_SSL" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_OPENSSL=ON -DEVENT__DISABLE_MBEDTLS=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_THREAD_SUPPORT" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_THREAD_SUPPORT=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_DEBUG_MODE" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_DEBUG_MODE=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_MM_REPLACEMENT" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_MM_REPLACEMENT=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_STATIC" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__LIBRARY_TYPE=STATIC -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_SHARED" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__LIBRARY_TYPE=SHARED -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON"

            else
              EVENT_CMAKE_OPTIONS=""
            fi
            EVENT_CMAKE_OPTIONS="$EVENT_CMAKE_OPTIONS -DMBEDTLS_ROOT_DIR=/usr/local/opt/mbedtls@2"

            mkdir -p build
            cd build
            echo [cmake]: cmake .. $EVENT_CMAKE_OPTIONS
            cmake .. $EVENT_CMAKE_OPTIONS || (rm -rf * && cmake .. $EVENT_CMAKE_OPTIONS)
            cmake --build .

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_minutes: 60
          shell: bash
          command: |
            ssh freebsd sh <<EOF
            cd $GITHUB_WORKSPACE
            JOBS=1
            export CTEST_PARALLEL_LEVEL=$JOBS
            export CTEST_OUTPUT_ON_FAILURE=1
            cd build
            if [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_STATIC" ]; then
              python3 ../test-export/test-export.py static
            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_SHARED" ]; then
              python3 ../test-export/test-export.py shared
            else
              cmake --build . --target verify
            fi
            EOF

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: freebsd-${{ matrix.release }}-cmake-${{ matrix.EVENT_MATRIX }}-build
          path: build

  freebsd-autotools-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci/freebsd skip') && !contains(github.event.head_commit.message, 'ci/freebsd/autotools skip')"
    strategy:
      fail-fast: false
      matrix:
        release: ["13.2"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: freebsd-${{ matrix.release }}-autotools-v1


      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: |
            pkg install -y  mbedtls  python3 autoconf automake libtool pkgconf
          usesh: true
          run: |
            ./autogen.sh
            mkdir -p build
            cd build
            echo [configure]: ../configure
            ../configure
            make

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_minutes: 60
          shell: bash
          command: |
            ssh freebsd sh <<EOF
            cd $GITHUB_WORKSPACE
            JOBS=1
            cd build
            make verify
            EOF

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: freebsd-${{ matrix.release }}-autotools-${{ matrix.EVENT_MATRIX }}-build
          path: build

  openbsd-cmake-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci/openbsd skip') && !contains(github.event.head_commit.message, 'ci/openbsd/cmake skip')"
    strategy:
      fail-fast: false
      matrix:
        release: [
          # 6.9 has some issues with autoconf/autotools [1].
          #   [1]: https://github.com/libevent/libevent/pull/1326#issuecomment-1229531718
          #"6.9",
          "",
        ]
        EVENT_MATRIX:
          - NONE
          - NO_SSL
          - DISABLE_OPENSSL
          - DISABLE_THREAD_SUPPORT
          - DISABLE_DEBUG_MODE
          - DISABLE_MM_REPLACEMENT
          - TEST_EXPORT_STATIC
          # For now this test is disabled due to incorrect library paths [1].
          #   [1]: https://github.com/libevent/libevent/pull/1326#issuecomment-1245159690
          #
          # - TEST_EXPORT_SHARED

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: openbsd-${{ matrix.release }}-cmake-${{ matrix.EVENT_MATRIX }}-v1

      - name: Build
        uses: vmactions/openbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: |
            pkg_add  mbedtls cmake python3
          usesh: true
          run: |
            if [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_OPENSSL" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_OPENSSL=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "NO_SSL" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_OPENSSL=ON -DEVENT__DISABLE_MBEDTLS=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_THREAD_SUPPORT" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_THREAD_SUPPORT=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_DEBUG_MODE" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_DEBUG_MODE=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "DISABLE_MM_REPLACEMENT" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_MM_REPLACEMENT=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_STATIC" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__LIBRARY_TYPE=STATIC -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON"

            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_SHARED" ]; then
              EVENT_CMAKE_OPTIONS="-DEVENT__LIBRARY_TYPE=SHARED -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON"

            else
              EVENT_CMAKE_OPTIONS=""
            fi
            EVENT_CMAKE_OPTIONS="$EVENT_CMAKE_OPTIONS -DMBEDTLS_ROOT_DIR=/usr/local/opt/mbedtls@2"

            mkdir -p build
            cd build
            echo [cmake]: cmake .. $EVENT_CMAKE_OPTIONS
            cmake .. $EVENT_CMAKE_OPTIONS || (rm -rf * && cmake .. $EVENT_CMAKE_OPTIONS)
            cmake --build .

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_minutes: 60
          shell: bash
          command: |
            ssh openbsd sh <<EOF
            ulimit -n 102400
            cd $GITHUB_WORKSPACE
            JOBS=1
            export CTEST_PARALLEL_LEVEL=$JOBS
            export CTEST_OUTPUT_ON_FAILURE=1
            cd build
            if [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_STATIC" ]; then
              python3 ../test-export/test-export.py static
            elif [ "${{ matrix.EVENT_MATRIX }}" == "TEST_EXPORT_SHARED" ]; then
              python3 ../test-export/test-export.py shared
            else
              cmake --build . --target verify
            fi
            EOF

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: openbsd-${{ matrix.release }}-cmake-${{ matrix.EVENT_MATRIX }}-build
          path: build

  openbsd-autotools-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci/openbsd skip') && !contains(github.event.head_commit.message, 'ci/openbsd/autotools skip')"
    strategy:
      fail-fast: false
      matrix:
        release: [""]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: openbsd-${{ matrix.release }}-autotools-v1


      - name: Build
        uses: vmactions/openbsd-vm@v1
        with:
          release: ${{ matrix.release }}
          prepare: |
            pkg_add  mbedtls  python3 automake-1.16.5  autoconf-2.71  libtool pkgconf
          usesh: true
          run: |
            export AUTOMAKE_VERSION=1.16
            export AUTOCONF_VERSION=2.71

            ./autogen.sh
            mkdir -p build
            cd build
            echo [configure]: ../configure
            ../configure
            make V=1

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_minutes: 60
          shell: bash
          command: |
            ssh openbsd sh <<EOF
            sysctl kern.maxfiles=$(($(sysctl -n kern.maxfiles) * 2))
            cd $GITHUB_WORKSPACE
            JOBS=1
            cd build
            make verify
            EOF

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: openbsd-${{ matrix.release }}-autotools-${{ matrix.EVENT_MATRIX }}-build
          path: build

  # ABI job without deploy
  abi-job:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Dependencies
        run:
          sudo apt install
            abi-tracker
            abi-monitor
            abi-dumper
            abi-compliance-checker
            pkgdiff
            vtable-dumper
      # FIXME: clone git repo or report to debian
      - name: Patch abi-compliance-checker to avoid endless loop
        run: sudo patch /usr/bin/abi-compliance-checker < extra/abi-check/debian.patch
      - name: Generate
        shell: bash
        run: |
          ./extra/abi-check/abi_check.sh
        env:
          ABI_CHECK_ROOT: /tmp/le-abi-root
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build
          path: /tmp/le-abi-root
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: /tmp/le-abi-root/work/abi-check
