---
name: build

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
  push:
    branches:
      - android-ci
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'

permissions: read-all

jobs:
  android-cmake-job:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci/macos skip') && !contains(github.event.head_commit.message, 'ci/macos/cmake skip')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ matrix.os }}-cmake-${{ matrix.EVENT_MATRIX }}-v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install latest NDK
        run: |
          latest_ndk=$(sdkmanager --list | grep -o "ndk;[0-9.]*" | sort -V | tail -1)
          echo "Installing $latest_ndk"
          sdkmanager "$latest_ndk"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$(echo $latest_ndk | cut -d';' -f2)" >> $GITHUB_ENV

      - name: Bash
        shell: bash
        run: |
          mkdir build && cd build
          echo [cmake]: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake
          cmake --build .
