---
name: cancel

on:
  workflow_run:
    workflows:
      - build
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-18.04
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          workflow_id: ${{ github.event.workflow.id }}
